# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(825, 542)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.refView = QtWidgets.QTableView(self.centralwidget)
        self.refView.setGeometry(QtCore.QRect(9, 178, 807, 89))
        self.refView.setObjectName("refView")
        self.subDataChangeButton = QtWidgets.QPushButton(self.centralwidget)
        self.subDataChangeButton.setGeometry(QtCore.QRect(560, 273, 80, 25))
        self.subDataChangeButton.setObjectName("subDataChangeButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 147, 77, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 273, 85, 17))
        self.label_2.setObjectName("label_2")
        self.unsubDataChangeButton = QtWidgets.QPushButton(self.centralwidget)
        self.unsubDataChangeButton.setGeometry(QtCore.QRect(724, 273, 92, 25))
        self.unsubDataChangeButton.setObjectName("unsubDataChangeButton")
        self.disconnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectButton.setGeometry(QtCore.QRect(690, 10, 84, 25))
        self.disconnectButton.setObjectName("disconnectButton")
        self.refAttrButton = QtWidgets.QPushButton(self.centralwidget)
        self.refAttrButton.setGeometry(QtCore.QRect(710, 150, 80, 25))
        self.refAttrButton.setObjectName("refAttrButton")
        self.logTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.logTextEdit.setGeometry(QtCore.QRect(9, 400, 807, 89))
        self.logTextEdit.setObjectName("logTextEdit")
        self.subView = QtWidgets.QTableView(self.centralwidget)
        self.subView.setGeometry(QtCore.QRect(9, 304, 807, 90))
        self.subView.setObjectName("subView")
        self.addressComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.addressComboBox.setGeometry(QtCore.QRect(9, 9, 401, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addressComboBox.sizePolicy().hasHeightForWidth())
        self.addressComboBox.setSizePolicy(sizePolicy)
        self.addressComboBox.setEditable(True)
        self.addressComboBox.setObjectName("addressComboBox")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(590, 10, 80, 25))
        self.connectButton.setObjectName("connectButton")
        self.connSettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.connSettingsButton.setGeometry(QtCore.QRect(430, 10, 144, 25))
        self.connSettingsButton.setObjectName("connSettingsButton")
        self.endpointsButton = QtWidgets.QPushButton(self.centralwidget)
        self.endpointsButton.setGeometry(QtCore.QRect(280, 150, 132, 25))
        self.endpointsButton.setObjectName("endpointsButton")
        self.attrView = QtWidgets.QTreeView(self.centralwidget)
        self.attrView.setGeometry(QtCore.QRect(385, 39, 401, 101))
        self.attrView.setObjectName("attrView")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(9, 40, 361, 101))
        self.treeView.setObjectName("treeView")
        self.writeButton = QtWidgets.QPushButton(self.centralwidget)
        self.writeButton.setGeometry(QtCore.QRect(190, 150, 80, 25))
        self.writeButton.setObjectName("writeButton")
        self.readButton = QtWidgets.QPushButton(self.centralwidget)
        self.readButton.setGeometry(QtCore.QRect(100, 150, 80, 25))
        self.readButton.setObjectName("readButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.subDataChangeButton.setText(_translate("mainWindow", "Subscribe"))
        self.label.setText(_translate("mainWindow", "References"))
        self.label_2.setText(_translate("mainWindow", "Subscription"))
        self.unsubDataChangeButton.setText(_translate("mainWindow", "Unsubscribe"))
        self.disconnectButton.setText(_translate("mainWindow", "Disconnect"))
        self.refAttrButton.setText(_translate("mainWindow", "Refresh"))
        self.connectButton.setText(_translate("mainWindow", "Connect"))
        self.connSettingsButton.setText(_translate("mainWindow", "Connection settings"))
        self.endpointsButton.setText(_translate("mainWindow", "Query Endopoints"))
        self.writeButton.setText(_translate("mainWindow", "Write"))
        self.readButton.setText(_translate("mainWindow", "Read"))
